team1project/team1project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]

team1project/todoapp/urls.py
'''
Configure available urls in todoapp and their respective views
'''

from django.urls import path, include
from django.contrib.auth.views import LogoutView
from .views import index, ProfileSettings, EditProfile, register, task_archive
from . import views


urlpatterns = [
	path('', index, name='index'),
	path('select2/', include('django_select2.urls')),
	path('profile_settings/', ProfileSettings.as_view(), name='profile_settings'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('register/', register, name='register'),
	path('tasks/', views.task_view, name='task_view'),
	path('task_archive/', task_archive, name='task_archive'),
	path('tasks/delete/<int:task_id>/', views.delete_task, name='delete_task'),
	path('tasks/archive/<int:task_id>/', views.archive_task, name='archive_task'),
	path('tasks/restore/<int:task_id>/', views.restore_task, name='restore_task'),
	path('tasks/add/', views.add_task, name='add_task'),
	path('tasks/edit/<int:task_id>/', views.edit_task, name='edit_task'),
	path('tasks/share/<int:task_id>', views.share_task, name='share_task'),
	path('shared_task/<int:task_id>', views.shared_task_view, name='shared_task_view'),
	path('shared_task/accept_request_link/<int:task_id>',
		views.accept_task_link, name='accept_request_link'),
	path('tasks/accept/<int:request_id>/', views.accept_task, name='accept_task'),
	path('tasks/exit/<int:task_id>/', views.exit_task, name='exit_task'),
	path('webpush/', include('webpush.urls')),
	path('home/', views.calender_view , name='home'),
	path('edit_profile/', EditProfile.as_view(), name="edit_profile"),
	path('webpush-sw.js', views.service_worker, name='service_worker'),
	path('save-subscription/', views.save_subscription, name='save_subscription'),
	path('service-worker.js', views.service_worker, name='service_worker'),
	path('about/', views.about, name='about'),
]

team1project/todoapp/models.py
"""Module that contains task objects models stored in the DB for the taskapp."""
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

User = get_user_model()

class Category(models.Model):
    """
    Represents a category that tasks can be grouped into.

    Fields:
        name (CharField): The name of the category."""
    name = models.CharField(max_length=50)
    objects = models.Manager()

    def __str__(self):
        return str(self.name or "")


class Task(models.Model):
    """
    Represents a task with details, collaborators, progress tracking, and notification settings.

    Fields:
        name (CharField): Name/title of the task.
        creator (ForeignKey): User who created the task.
        description (TextField): Description of the task.
        due_date (DateTimeField): Deadline for the task.
        progress (IntegerField): Progress percentage (0–100).
        is_completed (BooleanField): Whether the task is marked as complete.
        is_archived (BooleanField):Whether the task is archived(based on completion and due date).
        categories (ManyToManyField): Categories the task belongs to.
        assigned_users (ManyToManyField): Users assigned to this task.
        notifications_enabled (BooleanField): Whether notifications are enabled for the task.
        notification_time (IntegerField):When to send the notification(in minutes before due date).
        notification_type (CharField): Type of notification to send (push or email)."""
    name = models.CharField(max_length=255)
    objects = models.Manager()
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    due_date = models.DateTimeField()
    progress = models.IntegerField(default=0)
    is_completed = models.BooleanField(default=False)
    is_archived = models.BooleanField(default=False)
    ignore_archive = models.BooleanField(default=False)
    categories = models.ManyToManyField(Category, related_name="tasks", blank=True)
    assigned_users = models.ManyToManyField(User, related_name="assigned_tasks")
    notifications_enabled = models.BooleanField(default=False)
    NOTIFICATION_TIMES = [
        (10, '10 minutes before'),
        (60, '1 hour before'),
        (1440, '1 day before'),
    ]

    NOTIFICATION_TYPES = [
        ('push', 'Push Notification'),
        ('email', 'Email Notification'),
    ]

    notification_time = models.IntegerField(choices=NOTIFICATION_TIMES, default=60)
    notification_type = models.CharField(
        max_length=10,
        choices=NOTIFICATION_TYPES,
        default='push'
    )

    def save(self, *args, **kwargs):
        self.is_completed = self.progress == 100

        if self.ignore_archive:
            pass
        elif self.is_archived:
            pass
        elif self.is_completed and self.due_date < timezone.now():
            self.is_archived = True
        else:
            self.is_archived = False
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.name or "")


class SubTask(models.Model):
    """Represents a subtask that is part of a larger task.

    Fields:
        name (CharField): Name/title of the subtask.
        task (ForeignKey): The parent task this subtask belongs to.
        is_completed (BooleanField): Whether the subtask is marked as complete.
        assigned_users (ManyToManyField): Users assigned to this subtask."""
    name = models.CharField(max_length=255)
    objects = models.Manager()
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="subtasks")
    is_completed = models.BooleanField(default=False)
    assigned_users = models.ManyToManyField(User, related_name="assigned_subtasks")


class TaskProgress(models.Model):
    """Represents a user's progress update for a specific task.

    Fields:
        task (ForeignKey): The task this progress update is related to.
        user (ForeignKey): The user who submitted the progress update.
        progress (IntegerField): Progress percentage (0–100), default is 0.
        update_time (DateTimeField): Timestamp when the progress was last updated."""
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="progress_update")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    objects = models.Manager()
    progress = models.IntegerField(default=0)
    update_time = models.DateTimeField(auto_now=True)


class TaskCollabRequest(models.Model):
    """Represents a collaboration request sent from one user to another for a specific task.

    Fields:
        task (ForeignKey): The task for which collaboration is requested.
        from_user (ForeignKey): The user sending the collaboration request.
        to_user (ForeignKey): The user receiving the collaboration request."""
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    objects = models.Manager()
    from_user = models.ForeignKey(User, related_name="from_user", on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name="to_user", on_delete=models.CASCADE)


class WebPushSubscription(models.Model):
    """Stores a user's web push subscription information for push notifications.

    Fields:
        user (OneToOneField): The user associated with this subscription.
        subscription_info (JSONField): The subscription details needed to send
        web push notifications.
        created_at (DateTimeField): Timestamp when the subscription was created."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    objects = models.Manager()
    subscription_info = models.JSONField()  # If you're using Django 3.1+
    created_at = models.DateTimeField(auto_now_add=True)

team1project/todoapp/forms.py
'''
This module contains forms for user creation, task creation,
requests, and filtering tasks
'''

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

from django_select2.forms import ModelSelect2Widget

from .models import Task, Category, TaskCollabRequest

User = get_user_model()



# pylint: disable=E1101
# pylint: disable=R0903
# pylint: disable=R0901

class CustomUserCreationForm(UserCreationForm):
    '''
    Form for processing users with an email

    Attributes: 
        email: an optional EmailField for users
    '''

    email = forms.EmailField(required=False, help_text="(Optional)")

    class Meta:
        '''
        House metadata for user creation

        Model: user
        fields:
            username: Username configuration
            email: email to use for email notifications
            password1: password use
            password2: password for confirmation
        '''
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class CustomAuthenticationForm(AuthenticationForm):
    '''
    Custom form for processing users

    Attributes: 
        username: TextInput for user to enter username
        password: TextInput for user to enter password
    '''

    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
    )


class TaskForm(forms.ModelForm):
    '''
    Form for users to enter information on task

    Attributes: 
        categories: users can select multiple categories
        fields: name, description, due_date, progress, categories,
        and notifactions enabled button for creating or editing a task
    '''

    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        '''
        House metadata for task creation

        Model: user
        fields:
            name: Name of task
            description: Details of task
            due_date: Date where task is due by
            progress: Progress bar for tracking
            categories: Choose which category tasks is under
            notifications_enabled: Select which notifications to use
        '''

        model = Task
        fields = ['name', 'description', 'due_date', 'progress', 'categories',
        'notifications_enabled', 'notification_time', 'notification_type']
        widgets = {
            'due_date': forms.DateInput(attrs={'type': 'date'}),
            'progress': forms.NumberInput(attrs={'type': 'range',
            'min': '0', 'max': '100', 'step': '1', 'oninput': 'updateProgressLabel(this.value)'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Applys Bootstrap 'form-control'
        for field_name in ['name', 'description', 'due_date', 'progress']:
            if field_name in self.fields:
                self.fields[field_name].widget.attrs.update({'class': 'form-control'})


class TaskCollabForm(forms.ModelForm):
    '''
    Form for users to search users to share a task with

    Attributes: 
        user: the user sending the request
        task: the task that is being shared through a request
        to_user: the user that is sent request
    '''

    # Prevent the current user from showing up in the queryset
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.task = kwargs.pop('task', None)
        super().__init__(*args, **kwargs)

        # Start by excluding the current user and the task creator
        exclude_users = [self.user.id, self.task.creator.id]

        # Prevent current user from sending requests to users shared with the task
        assigned_users = list(self.task.assigned_users.values_list('id', flat=True))
        exclude_users.extend(assigned_users)

        # Exclude users who already have the task, shared, creator, or self
        user_queryset = User.objects.exclude(id__in=exclude_users)

        # Prevent a request from being sent to people with existing request
        if self.task:
            existing_requests = TaskCollabRequest.objects.filter(
                task=self.task,
            ).values_list('to_user', flat=True)
            user_queryset = user_queryset.exclude(id__in=existing_requests)

        self.fields['to_user'].queryset = user_queryset

    class Meta:
        '''
        House metadata for task collboration request

        Model: TaskCollabRequest
        fields:
            to_user: To whom the request is being sent to
        '''

        model = TaskCollabRequest
        fields = ['to_user']
        widgets = {'to_user': ModelSelect2Widget(model=User, search_fields=['username__icontains'])}



class FilterTasksForm(forms.Form):
    '''
    Form for filtering tasks based on categories selected

    Attributes: 
        user_category_filter: categories that user selected
            to filter tasks based on
    '''

    user_category_filter = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="Select categories:"
    )

team1project/todoapp/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="card p-4 shadow" style="max-width: 1200px; margin: 0 auto;">
        <div class="card-body">
            <p class="text-center mb-4" ><b>Welcome to To-Do List!</b></p>
            <hr>
            <p>Users need an app to help organize and track their tasks. Many people struggle today with handling busy schedules and responsibilities. Tracking tasks can also be stressful enough, especially for those who have many responsibilities. The To-Do List would be able to provide an environment to store, track, and suggest tasks.</p>
        </div>
    </div>        
    <h1 class="text-center mb-4" style="margin-top: 30px;">Meet Our Team</h1>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 justify-content-center">
        <!-- Developer Card 1 -->
        <div class="col">
            <div class="card h-100 text-center shadow">
                <img src="{% static '1.jpg' %}" class="card-img-top" alt="Dev 1">
                <div class="card-body">
                    <h5 class="card-title">Dev 1</h5>
                    <p class="card-text">Sam</p>
                </div>
            </div>
        </div>

        <!-- Developer Card 2 -->
        <div class="col">
            <div class="card h-100 text-center shadow">
                <img src="{% static '2.jpg' %}" class="card-img-top" alt="Dev 2">
                <div class="card-body">
                    <h5 class="card-title">Dev 2</h5>
                    <p class="card-text">James</p>
                </div>
            </div>
        </div>

        <!-- Developer Card 3 -->
        <div class="col">
            <div class="card h-100 text-center shadow">
                <img src="{% static '3.jpg' %}" class="card-img-top" alt="Dev 3">
                <div class="card-body">
                    <h5 class="card-title">Dev 3</h5>
                    <p class="card-text">Tarek</p>
                </div>
            </div>
        </div>

        <!-- Developer Card 4 -->
        <div class="col">
            <div class="card h-100 text-center shadow">
                <img src="{% static '4.jpg' %}" class="card-img-top" alt="Dev 4">
                <div class="card-body">
                    <h5 class="card-title">Dev 4</h5>
                    <p class="card-text">Noah</p>
                </div>
            </div>
        </div>

        <!-- Developer Card 5 -->
        <div class="col">
            <div class="card h-100 text-center shadow">
                <img src="{% static '5.jpg' %}" class="card-img-top" alt="Dev 5">
                <div class="card-body">
                    <h5 class="card-title">Dev 5</h5>
                    <p class="card-text">Marina</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

team1project/todoapp/templates/add_task.html
{% extends 'base.html' %}

{% block content %}
<div class="alert alert-info alert-dismissible fade show d-flex justify-content-between align-items-center flex-wrap gap-2 border border-dark custom-alert"  role="alert">
    <p class="mb-0">
      Here, you are able to create tasks so that you can add them to your personal calender. Please enter information about a given task in the fields below. If you wish to recieve reminders about the task (for example, when the deadline is approaching) please check the 'Reminders' box at the bottom of the form.
    </p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div> 

<div class="container mt-4">
    <h2 class="mb-4">{{ edit_mode|default:False|yesno:"Edit Task,Create a New Task" }}</h2>

    <div class="card p-4 shadow">
        <form method="post">
            {% csrf_token %}
            
            <div class="mb-3">
                <b>{{ form.name.label_tag }} </b>
                <br>
                {{ form.name }}
            </div>

            <div class="mb-3">
                <div class="mb-3">
                    <label for="id_description" class="form-label"><b>{{ form.description.label }}</b></label>
                    <br>
                    {{ form.description }}
                </div>
            </div>

            <div class="mb-3">
                <b>{{ form.due_date.label_tag }}</b>
                <br>
                {{ form.due_date }}
            </div>

            <div class="mb-3">
                <label for="id_progress_slider"><b>Progress:</b></label>
                <div class="d-flex align-items-center">
                    <input 
                        type="number" 
                        id="id_progress" 
                        name="progress" 
                        min="0" 
                        max="100" 
                        step="1" 
                        value="{{ form.progress.value|default:0 }}" 
                        class="form-control w-auto"
                    >
                    <input 
                        type="range" 
                        id="id_progress_slider" 
                        min="0" 
                        max="100" 
                        step="1" 
                        value="{{ form.progress.value|default:0 }}" 
                        class="form-range me-3"
                    >
                    
                </div>
            </div>
            

            <div class="mb-3">
                <b>{{ form.categories.label_tag }}</b>
                {{ form.categories }}
            </div>

            <div class="mb-3">
                {{ form.assigned_users.label_tag }}
                {{ form.assigned_users }}
            </div>

            <div class="mb-3">
                <b>{{ form.notifications_enabled.label_tag }}</b>
                <br>
                {{ form.notifications_enabled }}
            </div>

            <div id="notification-options" style="display: none;">
                <div class="mb-3">
                    <label><b>Notification Type:</b></label>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="notification_type" id="push_notification" value="push" checked>
                        <label class="form-check-label" for="push_notification">
                            Push Notifications
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="notification_type" id="email_notification" value="email">
                        <label class="form-check-label" for="email_notification">
                            Email Notifications
                        </label>
                    </div>
                </div>
            
                <div class="mb-3">
                    <b>{{ form.notification_time.label_tag }}</b>
                    <select class="form-select" name="notification_time" id="id_notification_time">
                        {% for value, label in form.fields.notification_time.choices %}
                            <option value="{{ value }}" {% if form.notification_time.value|stringformat:"s" == value|stringformat:"s" %}selected{% endif %}>
                                {{ label }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                
            </div>

            <button type="submit" class="btn btn-secondary">
                {{ edit_mode|default:False|yesno:"Update Task,Create Task" }}
            </button>

            <a href="{% url 'task_view' %}" name="Cancel" class="custom-dark-button" >Cancel</a>
        </form>
    </div>
</div>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        const slider = document.getElementById("id_progress_slider");
        const numberInput = document.getElementById("id_progress");

        // Update number when slider changes
        slider.addEventListener("input", function () {
            numberInput.value = slider.value;
        });

        // Update slider when number changes
        numberInput.addEventListener("input", function () {
            let value = parseInt(numberInput.value) || 0;
            value = Math.min(100, Math.max(0, value));
            numberInput.value = value;
            slider.value = value;
        });
    });
</script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const notificationsCheckbox = document.getElementById("id_notifications_enabled");
        const notificationOptions = document.getElementById("notification-options");
    
        function toggleNotificationOptions() {
            if (notificationsCheckbox.checked) {
                notificationOptions.style.display = "block";
            } else {
                notificationOptions.style.display = "none";
            }
        }
    
        notificationsCheckbox.addEventListener("change", toggleNotificationOptions);
    
        // Run it once in case the page is reloaded with it checked
        toggleNotificationOptions();
    });
</script>

<!-- for dismissable alerts -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
      // Find all dismissible alerts with a unique ID
      const alerts = document.querySelectorAll('[data-dismissible-id]');
  
      alerts.forEach(alert => {
        const alertId = alert.getAttribute('data-dismissible-id');
        const dismissed = localStorage.getItem(`dismissedAlert-${alertId}`);
  
        // Hide it if previously dismissed
        if (dismissed === 'true') {
          alert.remove(); // or alert.classList.add('d-none');
          return;
        }
  
        // Store dismissal on Bootstrap's alert close
        alert.addEventListener('closed.bs.alert', function () {
          localStorage.setItem(`dismissedAlert-${alertId}`, 'true');
        });
      });
    });
  </script>
  
{% endblock %}

team1project/todoapp/templates/edit_profile.html
{% extends 'base.html' %}
{% block content %}
<div class="card p-4 shadow" style="max-width: 1200px; margin: 0 auto;">
    <div class="card-body">
        <div class="row">
            <!-- Content Column -->
            <div class="col-md-12">
                <div class="d-flex justify-content-end">
                    <a href="{% url 'profile_settings' %}" class="btn btn-secondary" style="color: white; background-color: gray;">Cancel</a>
                </div>
                <h2 class="card-title" style="margin-bottom: 30px;">Profile Settings</h2>

                <form method="post">
                    {% csrf_token %}

                    <div class="profile-settings">
                        <label for="username">Username:</label>
                        <input style="margin-left: 10px; margin-top: 10px; margin-bottom: 10px;" type="text" name="username" class="form-control-6" value="{{user.username}}">
                        <br>

                        <label for="email">Email:</label>
                        <input style="margin-left: 45px; margin-top: 10px; margin-bottom: 10px;" type="text" name="email" class="form-control-6" value="{{user.email}}">
                        <br>

                        <label for="password">Passsword:</label>
                        <input style="margin-left: 5px; margin-top: 10px; margin-bottom: 10px;" type="text" name="password" class="form-control-6" value="************">
                    </div>
                    
                    <br>
                    <button type="submit" id="save-button" class="custom-dark-button" >Save Changes</button>
                    <button href="{% url 'index' %}" name="logout" class="btn btn-secondary" style="margin-left:5px;">Logout</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

team1project/todoapp/templates/index.html
{% extends 'base.html' %}
{% block title %}Welcome Page{% endblock %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'styles.css' %}">
{% endblock %}

{% block content %}
<div class="alert alert-info alert-dismissible fade show d-flex justify-content-between align-items-center flex-wrap gap-2 border border-dark custom-alert" role="alert">
    <p class="mb-0">
      Welcome to the To-Do List app! These alerts will appear to provide you with information on how to use the app and navigate each page. To dismiss this alert, click the 'x' on the right hand side of the message. 
    </p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>  

<!-- main box -->
<div class="card p-4 shadow" style="max-width: 1200px; margin: 0 auto;">
    <div class="card-body">
        <div class="row">
            <!-- left column: welcome text and login form -->
            <div class="col-md-6">
                <h2 class="card-title" style="margin-bottom: 10px;">Welcome!</h2>
                <hr>
                <p>This is the start of development of the To-Do List App.</p>

                {% if user.is_authenticated %}
                <div>
                    <p>For more information about the app and our team, please navigate to the "About" page by clicking on the navigation button 
                        in the top left corner. 
                    </p>
                </div>
                {% endif %}
                
                {% if not user.is_authenticated %}

                <!-- login form -->
                <form method="post" class="login-form" style= "margin-top: 30px;">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="custom-dark-button">Login</button>
                </form>

                <!-- register button -->
                <br>
                <div>
                    <p>If you have no account, sign up here:</p>
                    <a type='submit' class="btn btn-secondary" href="{% url 'register' %}">Register</a>
                </div>
                {% endif %}
            </div>

            <!-- right column: image-->
            <div class="col-md-6 d-flex justify-content-end align-items-center">
                <img src="{% static 'To-Do.jpeg' %}" alt="To-Do List" class="img-fluid rounded" style="max-width: 75%; height: auto;">
            </div>
        </div>
    </div>
</div>
{% endblock %}

team1project/todoapp/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="card p-4 shadow" style="max-width: 1200px; margin: 0 auto;">
    <div class="card-body">
        <div class="row">
            <!-- Content Column -->
            <div class="col-md-6">
                <h2 class="card-title" style="margin-bottom: 30px;">Profile Settings</h2>
                <form method="post" class="register-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Register</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

team1project/todoapp/templates/share_task.html
{% extends 'base.html' %}

{% block content %}
<div class="alert alert-info alert-dismissible fade show d-flex justify-content-between align-items-center flex-wrap gap-2 border border-dark custom-alert role="alert">
    <p class="mb-0">
      Here, you are able to share tasks so that other users can view details about a task and add it to their calender. You can share a task with a user by either entering their username or sending them the provided link. 
    </p>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>  

{% block head %}
    <!-- Help from ChatGPT -->
    {{ form.media.css }}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
    <style>
        /* Ensure Select2 dropdown takes full width */
        .select2-container {
            width: 50% !important;
        }
    </style>
    <script>
        $(document).ready(function() {
            $('.django-select2').select2();  // Apply Select2 styling
        });
    </script>
{% endblock %}

    <div class="container mt-4">
        <h2 class="mb-4">Share task "{{task.name }}"</h2>

        <div class="card p-4 shadow">
            {% if request.user.username != task.creator.username %}
                <p><b>Creator:</b> {{ task.creator.username }}</p>
            {% endif %}
            <p><b>Shared Users:</b></p>
            {% for user in task.assigned_users.all %}
                    <p>- {{ user.username }}</p>
                {% empty %}
                    <p>None</p>
            {% endfor %}
            <p><b>Link:</b> <br>{{ url }}</p>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn btn-secondary">Share Task</button>
                <a href="{% url 'task_view' %}" name="Cancel" class="custom-dark-button" >Cancel</a>
            </form>

        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        {{ form.media.js }}
    </div>
</body>
{% endblock %}